import Head from 'next/head'
import Image from 'next/image'
import LayoutComponent from '../component/layout/LayoutComponent'
import PosterComponent from '../component/poster/PosterComponent'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <PosterComponent />
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">PetLovers.com</a>
        </h1>
      </main> */}
    </div>
  )
}
