import Head from 'next/head'
import Image from 'next/image'
import BlogComponent from '../component/blog/BlogComponent'
import ContactUsAdvertise from '../component/contactusad/ContactUsAdvertise'
import CustomerAnalysis from '../component/customerAnalysis/CustomerAnalysis'
import LayoutComponent from '../component/layout/LayoutComponent'
import FacilityComponent from '../component/poster/FacilityComponent'
import PosterComponent from '../component/poster/PosterComponent'
import Services from '../component/services/Services'
import TrainerComponent from '../component/trainer/TrainerComponent'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <PosterComponent />
          <CustomerAnalysis />
          <ContactUsAdvertise />
          <Services />
          <FacilityComponent />
          <TrainerComponent />
          <BlogComponent /> 
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">PetLovers.com</a>
        </h1>
      </main> */}
    </div>
  )
}
